PROMPT_PAIRWISE="""You are a helpful assistant in evaluating the quality of the outputs for a given question and context. Your goal is to select the best output for the given question based on the provided context.
                
Select the Output (a) or Output (b) that is better for the given question. The two outputs are generated by two different AI chatbots respectively.
Do NOT provide any explanation for your choice.
Do NOT say both / neither are good.
You should answer using ONLY “Output (a)” or “Output (b)”. Do NOT output any other words.
Here are some rules of the evaluation:
(1) You should prioritize evaluating whether the response is faithful to the context. A response is faithful to the context if all of the factual information in the response is attributable to the context. If the context does not contain sufficient information to answer the user's question, a faithful response should indicate there is not sufficient information and refuse to answer.
(2) If one response is faithful while the other response is not, select the faithful response. 
(3) If both responses are equally faithful to the context, {criteria}
(4) You should avoid any potential bias and your judgment should be as objective as possible. For example, the order in which the outputs were presented should NOT affect your judgment, as Output (a) and Output (b) are **equally likely** to be the better.

# Instruction:
{question}
# Output (a):
{response_a}
# Output (b):
{response_b}
# Context:
{context}
# Which is better, Output (a) or Output (b)? Your response should be either “Output (a)” or “Output (b)”:"""

PROMPT_PAIRWISE_CONDITIONAL="""
You are a helpful assistant in evaluating the quality of the outputs for a given question and context. Your goal is to select the best output for the given question based on the provided context.Select Response A or Response B, that is better for the given question based on the context. The two responses are generated by two different AI chatbots respectively.

Select the Output (a) or Output (b) that is better for the given question. The two outputs are generated by two different AI chatbots respectively.
Do NOT provide any explanation for your choice.
Do NOT say both / neither are good.
Here are some rules of the evaluation:
(1) A response is faithful to the context if all of the factual information in the response is attributable to the context. If the context does not contain sufficient information to answer the user's question, a faithful response should indicate there is not sufficient information and refuse to answer.
(2) First, determine if Output (a) is faithful to the context. Write your response as **Output (a):** <yes/no>
(3) Second, determine if Output (b) is faithful to the context. Write your response as **Output (b):** <yes/no>
(4) If one response is faithful while the other response is not, select the faithful response. If both responses are equally faithful to the context, prioritize evaluating responses based on {criteria}.
(5) You should avoid any potential bias and your judgment should be as objective as possible. For example, the order in which the outputs were presented should NOT affect your judgment, as Output (a) and Output (b) are **equally likely** to be the better.

# Instruction:
{question}
# Output (a):
{response_a}
# Output (b):
{response_b}
# Context:
{context}

# Which is better, Output (a) or Output (b)? Your response should be first state "yes/no" for Output (a) faithfulness, then "yes/no" for Output (b) faithfulness, then either “Output (a)” or “Output (b)”:"""

PROMPT_PAIRWISE_GENERIC="""You are a helpful assistant in evaluating the quality of the outputs for a given instruction. Your goal is to select the best output for the given instruction.
                
Select the Output (a) or Output (b) that is better for the given instruction and context. The two outputs are generated by two different AI chatbots respectively.
Do NOT provide any explanation for your choice.
Do NOT say both / neither are good.
You should answer using ONLY “Output (a)” or “Output (b)”. Do NOT output any other words.
Here are some rules of the evaluation:
(1) You should prioritize evaluating on {criteria}
(2) Outputs should NOT contain more/less than what the instruction asks for, as such outputs do NOT precisely execute the instruction.
(3) You should avoid any potential bias and your judgment should be as objective as possible. For example, the order in which the outputs were presented should NOT affect your judgment, as Output (a) and Output (b) are **equally likely** to be the better.

# Instruction:
{question}
# Output (a):
{response_a}
# Output (b):
{response_b}
# Context:
{context}
# Which is better, Output (a) or Output (b)? Your response should be either “Output (a)” or “Output (b)”:"""

def pairwise_parsing(judge_output, flip=False):
    if not flip:
        if '(a)' in judge_output:
            return 1
        elif '(b)' in judge_output:
            return 2
        else:
            return -1
    else:
        if '(a)' in judge_output:
            return 2
        elif '(b)' in judge_output:
            return 1
        else:
            return -1

pairwise_parsing_conditional = pairwise_parsing

